# 2 pts Create a notebook, import Pandas, and import the data as a dataframe.

==> In next two cells I have Imported all the required package and also using pandas CSV function I have imported the dataset as well.

In [29]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import RandomForestClassifier

In [30]:
data = pd.read_csv('C:\\Users\\Mohan Kumar\\Downloads\\data\\adult.csv')
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

# 2 pts Copy all columns with empty values and replace all empty numeric fields with the average of its column in this new column.

==> copied all the numeric feilds to new numeric fields and replaced the zero's with the mode(it takes the most repeated value) of the column.

In [31]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
newdf = data.select_dtypes(include=numerics)
column_list = newdf.columns.values
for each_column in column_list:
    data[str(each_column) + '_new'] = newdf[str(each_column)].replace(0,newdf[str(each_column)].mode())
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,...,capital-loss,hours-per-week,native-country,Income,age_new,fnlwgt_new,education-num_new,capital-gain_new,capital-loss_new,hours-per-week_new
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,...,0,40,United-States,<=50K,39,77516,13,2174,0,40
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,...,0,13,United-States,<=50K,50,83311,13,0,0,13
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,...,0,40,United-States,<=50K,38,215646,9,0,0,40
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,...,0,40,United-States,<=50K,53,234721,7,0,0,40
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,...,0,40,Cuba,<=50K,28,338409,13,0,0,40
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,...,0,40,United-States,<=50K,37,284582,14,0,0,40
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,...,0,16,Jamaica,<=50K,49,160187,5,0,0,16
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,...,0,45,United-States,>50K,52,209642,9,0,0,45
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,...,0,50,United-States,>50K,31,45781,14,14084,0,50
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,...,0,40,United-States,>50K,42,159449,13,5178,0,40
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,...,0,80,United-States,>50K,37,280464,10,0,0,80
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,...,0,40,India,>50K,30,141297,13,0,0,40
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,...,0,30,United-States,<=50K,23,122272,13,0,0,30
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,...,0,50,United-States,<=50K,32,205019,12,0,0,50
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,...,0,40,?,>50K,40,121772,11,0,0,40
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,...,0,45,Mexico,<=50K,34,245487,4,0,0,45
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,...,0,35,United-States,<=50K,25,176756,9,0,0,35
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,...,0,40,United-States,<=50K,32,186824,9,0,0,40
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,...,0,50,United-States,<=50K,38,28887,7,0,0,50
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,...,0,45,United-States,>50K,43,292175,14,0,0,45
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,...,0,60,United-States,>50K,40,193524,16,0,0,60
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,...,0,20,United-States,<=50K,54,302146,9,0,0,20
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,...,0,40,United-States,<=50K,35,76845,5,0,0,40
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,...,2042,40,United-States,<=50K,43,117037,7,0,2042,40
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,...,0,40,United-States,<=50K,59,109015,9,0,0,40
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,...,0,40,United-States,>50K,56,216851,13,0,0,40
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,...,0,40,United-States,<=50K,19,168294,9,0,0,40
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,...,0,60,South,>50K,54,180211,10,0,0,60
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,...,0,80,United-States,<=50K,39,367260,9,0,0,80
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,...,0,40,United-States,<=50K,49,193366,9,0,0,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,...,0,99,United-States,<=50K,30,33811,13,0,0,99
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,...,0,60,United-States,>50K,34,204461,16,0,0,60
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,...,0,50,Japan,>50K,54,337992,13,0,0,50
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,...,0,39,United-States,<=50K,37,179137,10,0,0,39
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,...,0,35,United-States,<=50K,22,325033,8,0,0,35
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,...,0,55,United-States,>50K,34,160216,13,0,0,55
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,...,0,46,United-States,<=50K,30,345898,9,0,0,46
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,...,0,45,United-States,>50K,38,139180,13,15020,0,45
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,...,0,10,United-States,>50K,71,287372,16,0,0,10
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,...,0,40,United-States,<=50K,45,252208,9,0,0,40
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,...,0,32,United-States,<=50K,41,202822,9,0,0,32
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,...,0,25,United-States,<=50K,72,129912,9,0,0,25
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,...,0,48,United-States,<=50K,45,119199,12,0,0,48
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,...,0,30,United-States,<=50K,31,199655,14,0,0,30
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,...,0,20,United-States,>50K,39,111499,12,0,0,20
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,...,0,40,United-States,<=50K,37,198216,12,0,0,40
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,...,0,40,Mexico,<=50K,43,260761,9,0,0,40
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,...,0,60,United-States,<=50K,65,99359,15,1086,0,60
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,...,0,40,United-States,<=50K,43,255835,10,0,0,40
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,...,0,50,United-States,<=50K,43,27242,10,0,0,50
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,...,0,40,United-States,<=50K,32,34066,6,0,0,40
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,...,0,45,United-States,<=50K,43,84661,11,0,0,45
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,...,0,11,Taiwan,<=50K,32,116138,14,0,0,11
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,...,0,40,United-States,>50K,53,321865,14,0,0,40
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,...,0,40,United-States,<=50K,22,310152,10,0,0,40
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,...,0,38,United-States,<=50K,27,257302,12,0,0,38
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,...,0,40,United-States,>50K,40,154374,9,0,0,40
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,...,0,40,United-States,<=50K,58,151910,9,0,0,40
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,...,0,20,United-States,<=50K,22,201490,9,0,0,20
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,...,0,40,United-States,>50K,52,287927,9,15024,0,40

# 2pts Convert non-numeric columns to columns with an integer representations.

==> using FIT TRANSFORM of preprocessing label encoder.
==> And also used used Describe to check the row count and other details.

In [32]:
le = preprocessing.LabelEncoder()
newdf1 = data.select_dtypes(['object'])
for each_non_numeric in newdf1.columns.values:
    data[each_non_numeric] = le.fit_transform(data[each_non_numeric].values)
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,...,capital-loss,hours-per-week,native-country,Income,age_new,fnlwgt_new,education-num_new,capital-gain_new,capital-loss_new,hours-per-week_new
0,39,7,77516,9,13,4,1,1,4,1,...,0,40,39,0,39,77516,13,2174,0,40
1,50,6,83311,9,13,2,4,0,4,1,...,0,13,39,0,50,83311,13,0,0,13
2,38,4,215646,11,9,0,6,1,4,1,...,0,40,39,0,38,215646,9,0,0,40
3,53,4,234721,1,7,2,6,0,2,1,...,0,40,39,0,53,234721,7,0,0,40
4,28,4,338409,9,13,2,10,5,2,0,...,0,40,5,0,28,338409,13,0,0,40
5,37,4,284582,12,14,2,4,5,4,0,...,0,40,39,0,37,284582,14,0,0,40
6,49,4,160187,6,5,3,8,1,2,0,...,0,16,23,0,49,160187,5,0,0,16
7,52,6,209642,11,9,2,4,0,4,1,...,0,45,39,1,52,209642,9,0,0,45
8,31,4,45781,12,14,4,10,1,4,0,...,0,50,39,1,31,45781,14,14084,0,50
9,42,4,159449,9,13,2,4,0,4,1,...,0,40,39,1,42,159449,13,5178,0,40
10,37,4,280464,15,10,2,4,0,2,1,...,0,80,39,1,37,280464,10,0,0,80
11,30,7,141297,9,13,2,10,0,1,1,...,0,40,19,1,30,141297,13,0,0,40
12,23,4,122272,9,13,4,1,3,4,0,...,0,30,39,0,23,122272,13,0,0,30
13,32,4,205019,7,12,4,12,1,2,1,...,0,50,39,0,32,205019,12,0,0,50
14,40,4,121772,8,11,2,3,0,1,1,...,0,40,0,1,40,121772,11,0,0,40
15,34,4,245487,5,4,2,14,0,0,1,...,0,45,26,0,34,245487,4,0,0,45
16,25,6,176756,11,9,4,5,3,4,1,...,0,35,39,0,25,176756,9,0,0,35
17,32,4,186824,11,9,4,7,4,4,1,...,0,40,39,0,32,186824,9,0,0,40
18,38,4,28887,1,7,2,12,0,4,1,...,0,50,39,0,38,28887,7,0,0,50
19,43,6,292175,12,14,0,4,4,4,0,...,0,45,39,1,43,292175,14,0,0,45
20,40,4,193524,10,16,2,10,0,4,1,...,0,60,39,1,40,193524,16,0,0,60
21,54,4,302146,11,9,5,8,4,2,0,...,0,20,39,0,54,302146,9,0,0,20
22,35,1,76845,6,5,2,5,0,2,1,...,0,40,39,0,35,76845,5,0,0,40
23,43,4,117037,1,7,2,14,0,4,1,...,2042,40,39,0,43,117037,7,0,2042,40
24,59,4,109015,11,9,0,13,4,4,0,...,0,40,39,0,59,109015,9,0,0,40
25,56,2,216851,9,13,2,13,0,4,1,...,0,40,39,1,56,216851,13,0,0,40
26,19,4,168294,11,9,4,3,3,4,1,...,0,40,39,0,19,168294,9,0,0,40
27,54,0,180211,15,10,2,0,0,1,1,...,0,60,35,1,54,180211,10,0,0,60
28,39,4,367260,11,9,0,4,1,4,1,...,0,80,39,0,39,367260,9,0,0,80
29,49,4,193366,11,9,2,3,0,4,1,...,0,40,39,0,49,193366,9,0,0,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,0,33811,9,13,4,0,1,1,0,...,0,99,39,0,30,33811,13,0,0,99
32532,34,4,204461,10,16,2,10,0,4,1,...,0,60,39,1,34,204461,16,0,0,60
32533,54,4,337992,9,13,2,4,0,1,1,...,0,50,24,1,54,337992,13,0,0,50
32534,37,4,179137,15,10,0,1,4,4,0,...,0,39,39,0,37,179137,10,0,0,39
32535,22,4,325033,2,8,4,11,3,2,1,...,0,35,39,0,22,325033,8,0,0,35
32536,34,4,160216,9,13,4,4,1,4,0,...,0,55,39,1,34,160216,13,0,0,55
32537,30,4,345898,11,9,4,3,1,2,1,...,0,46,39,0,30,345898,9,0,0,46
32538,38,4,139180,9,13,0,10,4,2,0,...,0,45,39,1,38,139180,13,15020,0,45
32539,71,0,287372,10,16,2,0,0,4,1,...,0,10,39,1,71,287372,16,0,0,10
32540,45,7,252208,11,9,5,1,3,4,0,...,0,40,39,0,45,252208,9,0,0,40
32541,41,0,202822,11,9,5,0,1,2,0,...,0,32,39,0,41,202822,9,0,0,32
32542,72,0,129912,11,9,2,0,0,4,1,...,0,25,39,0,72,129912,9,0,0,25
32543,45,2,119199,7,12,0,10,4,4,0,...,0,48,39,0,45,119199,12,0,0,48
32544,31,4,199655,12,14,0,8,1,3,0,...,0,30,39,0,31,199655,14,0,0,30
32545,39,2,111499,7,12,2,1,5,4,0,...,0,20,39,1,39,111499,12,0,0,20
32546,37,4,198216,7,12,0,13,1,4,0,...,0,40,39,0,37,198216,12,0,0,40
32547,43,4,260761,11,9,2,7,0,4,1,...,0,40,26,0,43,260761,9,0,0,40
32548,65,6,99359,14,15,4,10,1,4,1,...,0,60,39,0,65,99359,15,1086,0,60
32549,43,7,255835,15,10,0,1,2,4,0,...,0,40,39,0,43,255835,10,0,0,40
32550,43,6,27242,15,10,2,3,0,4,1,...,0,50,39,0,43,27242,10,0,0,50
32551,32,4,34066,0,6,2,6,0,0,1,...,0,40,39,0,32,34066,6,0,0,40
32552,43,4,84661,8,11,2,12,0,4,1,...,0,45,39,0,43,84661,11,0,0,45
32553,32,4,116138,12,14,4,13,1,1,1,...,0,11,36,0,32,116138,14,0,0,11
32554,53,4,321865,12,14,2,4,0,4,1,...,0,40,39,1,53,321865,14,0,0,40
32555,22,4,310152,15,10,4,11,1,4,1,...,0,40,39,0,22,310152,10,0,0,40
32556,27,4,257302,7,12,2,13,5,4,0,...,0,38,39,0,27,257302,12,0,0,38
32557,40,4,154374,11,9,2,7,0,4,1,...,0,40,39,1,40,154374,9,0,0,40
32558,58,4,151910,11,9,6,1,4,4,0,...,0,40,39,0,58,151910,9,0,0,40
32559,22,4,201490,11,9,4,1,3,4,1,...,0,20,39,0,22,201490,9,0,0,20
32560,52,5,287927,11,9,2,4,5,4,0,...,0,40,39,1,52,287927,9,15024,0,40

In [33]:
data.describe()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,...,capital-loss,hours-per-week,native-country,Income,age_new,fnlwgt_new,education-num_new,capital-gain_new,capital-loss_new,hours-per-week_new
count,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,...,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,3.868892,189778.366512,10.298210,10.080679,2.611836,6.572740,1.446362,3.665858,0.669205,...,87.303830,40.437456,36.718866,0.240810,38.581647,189778.366512,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.455960,105549.977697,3.870264,2.572720,1.506222,4.228857,1.606771,0.848806,0.470506,...,402.960219,12.347429,7.823782,0.427581,13.640433,105549.977697,2.572720,7385.292085,402.960219,12.347429
min,17.000000,0.000000,12285.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,17.000000,12285.000000,1.000000,0.000000,0.000000,1.000000
25%,28.000000,4.000000,117827.000000,9.000000,9.000000,2.000000,3.000000,0.000000,4.000000,0.000000,...,0.000000,40.000000,39.000000,0.000000,28.000000,117827.000000,9.000000,0.000000,0.000000,40.000000
50%,37.000000,4.000000,178356.000000,11.000000,10.000000,2.000000,7.000000,1.000000,4.000000,1.000000,...,0.000000,40.000000,39.000000,0.000000,37.000000,178356.000000,10.000000,0.000000,0.000000,40.000000
75%,48.000000,4.000000,237051.000000,12.000000,12.000000,4.000000,10.000000,3.000000,4.000000,1.000000,...,0.000000,45.000000,39.000000,0.000000,48.000000,237051.000000,12.000000,0.000000,0.000000,45.000000
max,90.000000,8.000000,1484705.000000,15.000000,16.000000,6.000000,14.000000,5.000000,4.000000,1.000000,...,4356.000000,99.000000,41.000000,1.000000,90.000000,1484705.000000,16.000000,99999.000000,4356.000000,99.000000

# 2 pts Convert the data to a numpy array

==> using Numpy converted the data into array's.

==> training data contains all the array of the given datasets which exclude's INCOME column(Vector result)

In [34]:

training_data = np.array(data)
training_data = training_data[:,[3,5,6,7,8,9,13,15,16,17,18,19,20]]
training_data

array([[    9,     4,     1, ...,  2174,     0,    40],
       [    9,     2,     4, ...,     0,     0,    13],
       [   11,     0,     6, ...,     0,     0,    40],
       ...,
       [   11,     6,     1, ...,     0,     0,    40],
       [   11,     4,     1, ...,     0,     0,    20],
       [   11,     2,     4, ..., 15024,     0,    40]], dtype=int64)

==> In training Result I am storing the INCOME(vector result)

In [35]:
training_result = np.array(data)
training_result = training_result[:,[14]]
training_result

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]], dtype=int64)

# 2 pts Divide the data into a training and test set.

==>here we are splitting the data into training and test set.

In [36]:
from sklearn.cross_validation import train_test_split
training_data1, test_data, training_result1, test_result = train_test_split(training_data, training_result, test_size=0.33, random_state=0)
training_data1

array([[  15,    4,    1, ...,    0,    0,   15],
       [  11,    4,    5, ..., 8614,    0,   40],
       [   6,    0,    7, ...,    0,    0,   40],
       ...,
       [  15,    5,   12, ...,    0,    0,   40],
       [  10,    2,    4, ..., 7688,    0,   45],
       [  15,    4,    8, ..., 2597,    0,   48]], dtype=int64)

In [37]:
training_result1

array([[0],
       [1],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

# 2 pts Run a random forest on the training set.

==> here Random forest has been trainned with training data and training result using FIT method

In [38]:
model = RandomForestClassifier(n_estimators=100 , oob_score = True , random_state = 42)
model.fit(training_data1,training_result1.ravel())

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=42, verbose=0, warm_start=False)

# 2 pts Compute the accuracy of predictions on the test set.

==> here we are using the model which we have created with training data and we are using the test data  to predict the vector result.

==>since, we have generated the output which was predicted by Random Forest we need to compare the generated output with test _ result for accuracy score(this is done using metrics accuracy).

In [39]:
output = model.predict(test_data)
output

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [40]:
metrics.accuracy_score(output,test_result)

0.85231714126186486

# classification Report on Income(> 50 and < 50).

In [41]:
from sklearn.metrics import classification_report
target_names = ['<50','>50']
classification_report(test_result,output,target_names=target_names)

'             precision    recall  f1-score   support\n\n        <50       0.88      0.93      0.90      8151\n        >50       0.73      0.62      0.67      2595\n\navg / total       0.85      0.85      0.85     10746\n'